# Generated by Django 4.0.6 on 2022-07-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabelsModel',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Наименование марки авто')),
            ],
            options={
                'verbose_name': 'Марки автомобилей',
                'verbose_name_plural': 'Марку автомобиля',
                'ordering': ['name'],
            },
        ),
    ]
