# Generated by Django 4.0.6 on 2022-07-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0003_alter_carsmodel_options_carsmodel_body_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания объявления'),
        ),
    ]
