# Generated by Django 4.0.6 on 2022-07-22 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Car', '0009_alter_carsmodel_engine_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель объявления'),
        ),
    ]
