# Generated by Django 4.0.6 on 2022-07-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0010_carsmodel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsmodel',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена авто'),
        ),
    ]
