# Generated by Django 4.0.6 on 2022-07-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0012_usercarrealation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercarrealation',
            options={'verbose_name': 'Отношение пользователя к объявлению', 'verbose_name_plural': 'Отношения пользователей к объявлениям'},
        ),
        migrations.AlterField(
            model_name='usercarrealation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Рейтинг'),
        ),
    ]
