# Generated by Django 4.0.6 on 2022-07-24 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Car', '0013_alter_usercarrealation_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCarRealation',
            new_name='UserCarsRelation',
        ),
        migrations.AddField(
            model_name='carsmodel',
            name='customers',
            field=models.ManyToManyField(related_name='rate_books', through='Car.UserCarsRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carsmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_book', to=settings.AUTH_USER_MODEL, verbose_name='Создатель объявления'),
        ),
    ]
