# Generated by Django 4.0.6 on 2022-07-24 22:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Car', '0014_rename_usercarrealation_usercarsrelation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsmodel',
            name='customers',
            field=models.ManyToManyField(related_name='rate_books', through='Car.UserCarsRelation', to=settings.AUTH_USER_MODEL, verbose_name='Оценка пользователей'),
        ),
    ]
