# Generated by Django 4.0.6 on 2022-07-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0015_alter_carsmodel_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercarsrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Рейтинг'),
        ),
    ]
