# Generated by Django 4.0.6 on 2022-07-24 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0016_alter_usercarsrelation_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercarsrelation',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='Car.carsmodel', verbose_name='Объявление о машине'),
        ),
    ]
