# Generated by Django 4.0.6 on 2022-07-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0018_alter_usercarsrelation_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsmodel',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3),
        ),
    ]
